### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by colagrosso**

### CODE REVIEW

**Comment by acabal** [comment]
Hi there, thanks for these.

For the epigraphs, can you restore the em dashes please? We prefer to have them in. But, what you can do is when an em dash separates the author and a work, you can replace that with a comma. For example, `Quinault⁠—<i epub:type="se:name.music.opera">Atys</i>` -> `Quinault, <i epub:type="se:name.music.opera">Atys</i>`.

You can just rebase the epigraph commit instead of adding another one, and force push to this PR. Thanks!

**Comment by colagrosso** [comment]
Hi, thanks a bunch for the quick review. I'll fix that commit on Sat, Jan 1.

**Comment by colagrosso** [comment]
Ok, the epigraphs should be fixed now.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
